### ISSUE TITLE
Can't start doom

### ISSUE THREAD

**Issue by azzamsa** [cristicbz/rust-doom#143]
Hi.

I have followed the build instruction. But it cannot start.
I got the wad via [shareware](http://www.pc-freak.net/files/doom-wad-files/Doom1.WAD) one.

```bash
rust-doom on  master is 📦 v0.0.9 via 🦀 v1.50.0
❯ env RUST_BACKTRACE=1 target/release/rs_doom --iwad doom1.wad
[INFO  engine::context] Creating system "tick"...
[INFO  engine::context] Creating system "frame_timers"...
[INFO  engine::context] Creating system "window"...
[INFO  winit::platform::platform::x11::window] Guessed window DPI factor: 1
[INFO  engine::context] Creating system "input"...
[INFO  engine::context] Creating system "entities"...
[INFO  engine::context] Creating system "transforms"...
[INFO  engine::context] Creating system "projections"...
[INFO  engine::context] Creating system "shaders"...
[INFO  engine::context] Creating system "uniforms"...
[INFO  engine::context] Creating system "meshes"...
[INFO  engine::context] Creating system "materials"...
[INFO  engine::context] Creating system "render_pipeline"...
[INFO  engine::context] Creating system "text_renderer"...
[INFO  engine::context] Creating system "wad"...
[INFO  wad::archive] Loading wad file '"doom1.wad"'...
[INFO  wad::archive] Loading metadata file '"assets/meta/doom.toml"'...
[INFO  wad::tex] Reading texture directory...
[INFO  wad::tex]     14 palettes
[INFO  wad::tex]     34 colormaps
[INFO  wad::tex] Reading 350 patches....
[INFO  wad::tex] Done in 1.59ms; 187 missing patches.
[INFO  wad::tex]    350 patches
[INFO  wad::tex] Reading & assembling textures...
[INFO  wad::tex]    125 textures in TEXTURE1
[INFO  wad::tex]      0 textures in TEXTURE2
[INFO  wad::tex] Done in 1.08ms.
[INFO  wad::tex]     54 flats
[INFO  wad::tex] Reading 483 sprites....
[INFO  wad::tex] Done in 3.19ms.
[INFO  wad::tex]    483 sprites
[INFO  game::wad_system] Loading initial level WadName("E1M1\u{0}\u{0}\u{0}\u{0}") (0)...
[INFO  wad::level] Reading level data for 'E1M1'...
[INFO  wad::level] Loaded level 'E1M1':
[INFO  wad::level]      138 things
[INFO  wad::level]      475 linedefs
[INFO  wad::level]      648 sidedefs
[INFO  wad::level]      467 vertices
[INFO  wad::level]      732 segs
[INFO  wad::level]      237 subsectors
[INFO  wad::level]      236 nodes
[INFO  wad::level]       85 sectors
[INFO  game::wad_system] Analysing level...
[INFO  wad::visitor] Computing dynamic sectors...
[ERROR wad::visitor] Unknown linedef special type: 48
[ERROR wad::visitor] Unknown linedef special type: 48
[ERROR wad::visitor] Unknown linedef special type: 48
[ERROR wad::visitor] Unknown linedef special type: 48
[ERROR wad::visitor] Unknown linedef special type: 48
[ERROR wad::visitor] Unknown linedef special type: 48
[ERROR wad::visitor] Unknown linedef special type: 48
[ERROR wad::visitor] Unknown linedef special type: 48
[INFO  wad::visitor] Finished computing dynamic sectors: num_dynamic_sectors=7 num_dynamic_linedefs=19
[INFO  engine::context] Creating system "game_shaders"...
[INFO  game::game_shaders] Building flats atlas...
[INFO  wad::tex] Flat atlas size: 512x256 (8, 3)
[INFO  game::game_shaders] Building walls atlas...
[INFO  wad::tex] Texture atlas size: Vector2 [1024, 512]
[INFO  game::game_shaders] Building sprite decorations atlas...
[INFO  wad::tex] Texture atlas size: Vector2 [128, 512]
[INFO  engine::context] Creating system "level"...
[INFO  game::level] Building new level...
[INFO  game::level] Walking level...
[INFO  game::level] Level built in 0.90ms:
        num_wall_quads = 926
        num_floor_polys = 237
        num_ceil_polys = 202
        num_sky_wall_quads = 46
        num_sky_floor_polys = 0
        num_sky_ceil_polys = 35
        num_decors = 129
        num_static_tris = 2527
        num_sky_tris = 205
        num_sprite_tris = 258
[INFO  game::level] Creating static meshes and models...
[INFO  engine::context] Creating system "hud"...
[INFO  engine::context] Creating system "player"...
[INFO  engine::context] Creating system "renderer"...
[INFO  engine::context] Setting up system "tick"...
[INFO  engine::context] Setting up system "frame_timers"...
[INFO  engine::context] Setting up system "window"...
[INFO  engine::context] Setting up system "input"...
[INFO  engine::context] Setting up system "entities"...
[INFO  engine::context] Setting up system "transforms"...
[INFO  engine::context] Setting up system "projections"...
[INFO  engine::context] Setting up system "shaders"...
[INFO  engine::context] Setting up system "uniforms"...
[INFO  engine::context] Setting up system "meshes"...
[INFO  engine::context] Setting up system "materials"...
[INFO  engine::context] Setting up system "render_pipeline"...
[INFO  engine::context] Setting up system "text_renderer"...
[INFO  engine::context] Setting up system "wad"...
[INFO  engine::context] Setting up system "game_shaders"...
[INFO  engine::context] Setting up system "level"...
[INFO  engine::context] Setting up system "hud"...
[INFO  engine::context] Setting up system "player"...
[INFO  engine::context] Setting up system "renderer"...
[INFO  engine::context] Context set up.
thread 'main' panicked at 'attempted to leave type `platform::platform::x11::util::input::PointerState` uninitialized, which is invalid', /home/user/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/mem/mod.rs:659:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:50:5
   3: winit::platform::platform::x11::util::input::<impl winit::platform::platform::x11::xdisplay::XConnection>::query_pointer
   4: winit::platform::platform::x11::EventsLoop::process_event
   5: <engine::input::Input as engine::system::System>::update
   6: <engine::type_list::Cons<HeadT,TailT> as engine::context::SystemList<(HeadIndicesT,TailIndicesT)>>::update_list
   7: <game::game::GameImpl<WadIndexT,ContextT> as game::game::Game>::run
   8: rs_doom::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[INFO  engine::context] Tearing down system "renderer"...
[INFO  engine::context] Tearing down system "player"...
[INFO  engine::context] Tearing down system "hud"...
[INFO  engine::context] Tearing down system "level"...
[INFO  engine::context] Tearing down system "game_shaders"...
[INFO  engine::context] Tearing down system "wad"...
[INFO  engine::context] Tearing down system "text_renderer"...
[INFO  engine::context] Tearing down system "render_pipeline"...
[INFO  engine::context] Tearing down system "materials"...
[INFO  engine::context] Tearing down system "meshes"...
[INFO  engine::context] Tearing down system "uniforms"...
[INFO  engine::context] Tearing down system "shaders"...
[INFO  engine::context] Tearing down system "projections"...
[INFO  engine::context] Tearing down system "transforms"...
[INFO  engine::context] Tearing down system "entities"...
[INFO  engine::context] Tearing down system "input"...
[INFO  engine::context] Tearing down system "window"...
[INFO  engine::context] Tearing down system "frame_timers"...
[INFO  engine::context] Tearing down system "tick"...
[INFO  engine::context] Context tore down.
[INFO  engine::context] Destroying system "renderer"...
[INFO  engine::context] Destroying system "player"...
[INFO  engine::context] Destroying system "hud"...
[INFO  engine::context] Destroying system "level"...
[INFO  engine::context] Destroying system "game_shaders"...
[INFO  engine::context] Destroying system "wad"...
[INFO  engine::context] Destroying system "text_renderer"...
[INFO  engine::context] Destroying system "render_pipeline"...
[INFO  engine::context] Destroying system "materials"...
[INFO  engine::context] Destroying system "meshes"...
[INFO  engine::context] Destroying system "uniforms"...
[INFO  engine::context] Destroying system "shaders"...
[INFO  engine::context] Destroying system "projections"...
[INFO  engine::context] Destroying system "transforms"...
[INFO  engine::context] Destroying system "entities"...
[INFO  engine::context] Destroying system "input"...
[INFO  engine::context] Destroying system "window"...
[INFO  engine::context] Destroying system "frame_timers"...
[INFO  engine::context] Destroying system "tick"...
[INFO  engine::context] Context destroyed.

rust-doom on  master is 📦 v0.0.9 via 🦀 v1.50.0
❯
```

Is my machine too small for doom?

```
❯ macchina
    Kernel    —  Linux 4.19.0-14-amd64
    Distro    —  Debian GNU/Linux
    WM        —  i3
    Packages  —  2138
    Shell     —  /usr/bin/fish
    Terminal  —  Tmux: server
    Uptime    —  7 hours
    CPU       —  Intel® Core™ i7-8565U CPU @ 1.80GHz (8)
    Memory    —  2.7 GB/15.9 GB
```

Thanks for doom.

**Comment by cristicbz** [comment]
Hi! No, haha, your machine is fine--you hardly need any hardware at all to run it. I think the dependencies are out of date, I'll try to update everything and see if that fixes it (it doesn't work for me either right now)

**Comment by cristicbz** [comment]
Hi @azzamsa ! I pushed a commit which upgrades to newest versions of everything. It was harder than anticipated, because newest version of glutin had a weird inversion of control where it wants to manage the event loop for you.

Please let me know if it works now!

**Comment by azzamsa** [comment]
It works!, thank for rust-doom.
